#!/bin/sh
# Create a link to this file at .git/hooks/pre-commit to
# force PEP8 validation prior to committing

exec 1>&2

EXIT=0

echo "Formatting code..."
make black
[[ $? != 0 ]] && EXIT=1

echo "Sorting imports..."
make isort
[[ $? != 0 ]] && EXIT=1

echo "Validating PEP8 compliance..."
make flake8
[[ $? != 0 ]] && EXIT=1

echo "Checking for missing migrations..."
make check-migrations
[[ $? != 0 ]] && EXIT=1

echo "Testing application..."
make test
[[ $? != 0 ]] && EXIT=1

[[ $EXIT != 0 ]] && printf "\nCOMMIT FAILED\n\n"

exit $EXIT
