[tool.black]
line-length = 88
exclude = "migrations"

[tool.isort]
combine_as_imports = true
include_trailing_comma = true
known_django = "django"
# known_first_party= ""
no_lines_before = "LOCALFOLDER"
profile = "black"
sections = "FUTURE,STDLIB,THIRDPARTY,DJANGO,FIRSTPARTY,LOCALFOLDER"
skip_gitignore = true

[tool.pytest.ini_options]
addopts = "--verbose --capture=no --maxfail=1 --cov --cov-report html"
DJANGO_SETTINGS_MODULE = "{{ project_name }}.settings.development"
python_files = "test_*.py"

[tool.coverage.run]
source = ["{{ project_name }}/"]
omit = [
   "*manage.py",
   "*/settings/base.py",
   "*/settings/development.py",
   "*/settings/production.py",
   "*/test_*",
   "*migrations/*",
   "*asgi.py",
   "*urls.py",
   "*wsgi.py",
   "*__init__.py",
   "*/__pycache__/*",
]
